name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Lua
        run: sudo apt-get update --quiet && sudo apt-get install --yes --no-install-recommends lua5.4
      - name: Validate
        run: make check LUA=lua5.4 LUAC=luac5.4
